services:
  erp_laravel:
    build:
      context: php
    container_name: erp_laravel
    command: sh -c "npm install && npm run build && npm run dev & php-fpm"
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "5173:5173"
    depends_on:
      - erp_db

  erp_nginx:
    image: nginx:stable-alpine
    container_name: erp_nginx
    restart: "no"
    ports:
      - "8082:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - erp_laravel

  erp_db:
    image: mariadb:10.6
    container_name: erp_mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - erp_db_data:/var/lib/mysql

  erp_react:
    image: node:22-alpine
    container_name: erp_react
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3060:3060"
    volumes:
      - ./react-app:/app
    depends_on:
      - erp_nginx

  erp_ollama:
    image: ollama/ollama
    container_name: erp_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: "2"

  erp_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: erp_phpmyadmin
    restart: "no"
    ports:
      - "8083:80"
    environment:
      PMA_HOST: erp_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - erp_db

volumes:
  erp_db_data:
  ollama_data:
